export const initialState = {
  isLogged: true,
  posts: {
    data: [
      {
        title: 'Announcement title 1',
        description: 'This is a description. You can use this section to describe the content',
        publicationDate: '2020-04-20',
        lastUpdate: '2020-05-19',
        authorEmail: 'aaa@bb.eu',
        status: 'draft',
        price: 55,
        phone: '888-777-666',
        image: 'https://source.unsplash.com/random',
        imageTitle: 'Image title1',
      },
      {
        title: 'Announcement title 2',
        description: 'This is a description. You can use this section to describe the content',
        publicationDate: '2020-04-20',
        lastUpdate: '2020-05-19',
        authorEmail: 'aaa@bb.eu',
        status: 'draft',
        price: 55,
        phone: '888-777-666',
        image: 'https://source.unsplash.com/random',
        imageTitle: 'Image title1',
      },
      {
        title: 'Announcement title 3',
        description: 'This is a description. You can use this section to describe the content',
        publicationDate: '2020-04-20',
        lastUpdate: '2020-05-19',
        authorEmail: 'aaa@bb.eu',
        status: 'draft',
        price: 55,
        phone: '888-777-666',
        image: 'https://source.unsplash.com/random',
        imageTitle: 'Image title1',
      },
      {
        title: 'Announcement title 4',
        description: 'This is a description. You can use this section to describe the content',
        publicationDate: '2020-04-20',
        lastUpdate: '2020-05-19',
        authorEmail: 'aaa@bb.eu',
        status: 'draft',
        price: 55,
        phone: '888-777-666',
        image: 'https://source.unsplash.com/random',
        imageTitle: 'Image title1',
      },
      {
        title: 'Announcement title 5',
        description: 'This is a description. You can use this section to describe the content',
        publicationDate: '2020-04-20',
        lastUpdate: '2020-05-19',
        authorEmail: 'aaa@bb.eu',
        status: 'draft',
        price: 55,
        phone: '888-777-666',
        image: 'https://source.unsplash.com/random',
        imageTitle: 'Image title1',
      },
      {
        title: 'Announcement title 6',
        description: 'This is a description. You can use this section to describe the content',
        publicationDate: '2020-04-20',
        lastUpdate: '2020-05-19',
        authorEmail: 'aaa@bb.eu',
        status: 'draft',
        price: 55,
        phone: '888-777-666',
        image: 'https://source.unsplash.com/random',
        imageTitle: 'Image title1',
      },

    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
